services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: brt_devops_interview
    ports:
      - "8000:8080" 
    env_file:
      - web/.env
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh" 
  django_pizza_db:
    image: postgres
    restart: always
    env_file:
      - web/.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data: 