apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django-postgres
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: django-postgres-pvc
      - name: postgres-secrets
        secret:
          secretName: postgres-secrets
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database
              name: postgres-secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secrets
