# Generated by Django 5.0.3 on 2024-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('toppings', models.CharField(choices=[('P', 'Pepperoni'), ('M', 'Mushrooms'), ('O', 'Onions'), ('S', 'Sausage'), ('B', 'Bacon'), ('G', 'Extra cheese'), ('', 'None')], default='', max_length=1)),
            ],
        ),
    ]
