# Generated by Django 5.0.3 on 2024-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_type',
            field=models.CharField(choices=[('P', 'Plain'), ('M', 'Meat'), ('V', 'Veggie'), ('MG', 'Margherita'), ('MS', 'Mushroom Spinach')], default='P', max_length=2),
        ),
    ]
