# Generated by Django 5.0.3 on 2024-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0002_remove_order_toppings_order_pizza_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_type',
            field=models.CharField(choices=[('Plain', 'Plain'), ('Meat', 'Meat'), ('Veggie', 'Veggie'), ('Margherita', 'Margherita'), ('Mushroom Spinach', 'Mushroom Spinach')], default='Plain'),
        ),
    ]
