# Generated by Django 5.0.3 on 2024-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0003_alter_order_pizza_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='No Comment', max_length=300),
        ),
    ]
